# Generated by Django 3.1.5 on 2021-01-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_series', models.FloatField(verbose_name='Серия карты')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты')),
                ('card_issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска карты')),
                ('card_expiration_date', models.DateTimeField(verbose_name='Дата окончания активности карты')),
                ('card_date_of_use', models.DateTimeField(verbose_name='Дата последнего использования карты')),
                ('card_bonus_amount', models.FloatField(blank=True, null=True, verbose_name='Сумма бонуса карты')),
                ('card_status', models.BinaryField(default=True, verbose_name='Статус карты')),
            ],
            options={
                'verbose_name': 'Бонусная карта',
                'verbose_name_plural': 'Бонусные карты',
                'ordering': ['-card_date_of_use'],
            },
        ),
    ]
