# Generated by Django 3.1.5 on 2021-01-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0002_auto_20210120_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='card_issue_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска карты'),
        ),
        migrations.AlterField(
            model_name='cardslist',
            name='card_status',
            field=models.BooleanField(default=True, verbose_name='Статус карты'),
        ),
    ]
