# Generated by Django 3.1.5 on 2021-01-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0003_auto_20210120_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='card_series',
            field=models.CharField(max_length=4, verbose_name='Серия карты'),
        ),
    ]
