# Generated by Django 3.1.5 on 2021-01-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0005_auto_20210120_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='card_number',
            field=models.IntegerField(verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='cardslist',
            name='card_series',
            field=models.IntegerField(verbose_name='Серия карты'),
        ),
    ]
