# Generated by Django 3.1.5 on 2021-01-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0007_auto_20210121_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='card_status',
            field=models.CharField(default='Не активна', max_length=12, verbose_name='Статус карты'),
        ),
    ]
