# Generated by Django 3.1.5 on 2021-01-31 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0008_auto_20210121_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carddetail',
            fields=[
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cardslist.cardslist')),
                ('date_last_use', models.DateTimeField(verbose_name='Дата последнего использования')),
                ('purchase_amount', models.IntegerField(verbose_name='Сумма последней покупки')),
                ('changing_amount_bonuses', models.IntegerField(verbose_name='Изменение суммы бонусов')),
            ],
            options={
                'verbose_name': 'Детали карты',
                'verbose_name_plural': 'Детали карт',
                'ordering': ['-changing_amount_bonuses'],
            },
        ),
    ]
