# Generated by Django 3.1.5 on 2021-02-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0008_auto_20210121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardslist',
            name='card_date_of_use',
            field=models.DateTimeField(default=None, verbose_name='Дата последнего использования карты'),
        ),
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_use', models.DateTimeField(verbose_name='Дата последнего использования')),
                ('purchase_amount', models.IntegerField(verbose_name='Сумма последней покупки')),
                ('changing_amount_bonuses', models.IntegerField(verbose_name='Изменение суммы бонусов')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardslist.cardslist')),
            ],
            options={
                'verbose_name': 'Детали карты',
                'verbose_name_plural': 'Детали карт',
                'ordering': ['-changing_amount_bonuses'],
            },
        ),
    ]
