# Generated by Django 3.1.5 on 2021-02-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardslist', '0009_auto_20210203_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardslist.cardslist', verbose_name='Карта'),
        ),
        migrations.AlterField(
            model_name='carddetail',
            name='date_last_use',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего использования'),
        ),
        migrations.AlterField(
            model_name='cardslist',
            name='card_date_of_use',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего использования карты'),
        ),
    ]
